spring.security.user.name=${SPRING_SECURITY_USER_NAME:user1}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:123456}

spring.data.mongodb.port=${SPRING_DATA_MONGODB_PORT:27017}
spring.data.mongodb.database=${SPRING_DATA_MONGODB_DATABASE:senior_database}
spring.data.mongodb.username=${SPRING_DATA_MONGODB_USERNAME:admin}
spring.data.mongodb.password=${SPRING_DATA_MONGODB_PASSWORD:admin}
spring.data.mongodb.authentication-database=${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
spring.data.mongodb.auto-index-creation=true
